name: 02 - Output Information
run-name: Run Output Information by @${{ github.actor }}
on: workflow_dispatch
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: echo "${{ toJson(github) }}"
