name: 06 - Variables
run-name: Run ${{ github.workflow }} - ${{ github.action }} by ${{ github.actor }}
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Output Variable
        run: echo "${{ vars.JARR_TEST_VARIABLE }}"
      - name: Output Secret
        run: echo "${{ secrets.JARR_TEST_SECRET }}"
