name: 07 - Reusable
run-name: Run ${{ github.workflow }} | ${{ github.action }} | ${{ github.actor }}
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files path
        required: true
        default: dist-files
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "Deploying system....";
          echo "${{ inputs.artifact-name }}"
