# Define the name of this workflow
name: First Workflow

# Define the triggers
on: workflow_dispatch

# Define the jobs for this workflow
jobs:
  # First job to handle greeting and goodbye
  fist-job:
    # Define the runner
    runs-on: ubuntu-latest
    # Steps for this job
    steps:
      - name: Print Greeting
        run: |
          echo "Hellow world";
      - name: Print Goodbye
        run: |
          echo "Good Bye";
    

